name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 6 * * *'   # Setiap hari 13:00 WIB
  workflow_dispatch:       # Bisa dijalankan manual

permissions:
  contents: write
  workflows: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Fork
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Add Upstream
        run: |
          git remote add upstream https://github.com/SigmaHQ/sigma.git
          git fetch upstream

      - name: Set Git Config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Merge Changes
        run: |
          git checkout master
          git merge upstream/master --strategy-option theirs || true

      - name: Push Changes
        run: |
          git push origin master
